version: '3'

vars:
  LZ4: '{{.LZ4 | default "lz4/1.9"}}'

includes:
  envmodule: ./EnvironmentModules.yml

tasks:
  compress-dir-lz4:
    - task: lz4
      vars:
        CMDS: 'tar cf - {{.DIR}} | lz4 > {{.DIR}}.tar.lz4'

  decompress-dir-lz4:
    - task: lz4
      vars:
        CMDS: 'lz4 -dc {{.DIR}} | tar xf -'

  lz4:
    - task: envmodule:run-inside
      vars:
        CMDS: '{{.CMDS}}'
        MODULE: '{{.LZ4}}'