version: '3'

vars:
  CONDA_MODULE: anaconda/3/2023.03

includes:
  envmodule:
    taskfile: ./EnvironmentModules.yml
    internal: true

tasks:
  create-env:
    desc: Create a conda env.
    summary: | 
      Create a conda env.

      Usage:
      ------
      $ module load task
      $ task -t $GROUP_HOME/tools/lab-tasks conda:create-env
    cmds:
      - task: envmodule:run-inside
        vars:
          CMDS: 'conda create {{.NAME}} {{.INSTALL}} -y'
          MODULE: '{{.CONDA_MODULE}}'
    requires:
      vars: [NAME, INSTALL]

  # TODO: Any benefit to activating vs. using conda run?
  run-in-conda-env:
    desc: Run command in conda env.
    internal: true
    silent: true
    cmds:
      - task: envmodule:run-inside
        vars:
          CMDS: 'source activate {{.PREFIX}} --stack && {{.CMDS}} && conda deactivate'
          MODULE: '{{.CONDA_MODULE}}'
    requires:
      vars: [CMDS, PREFIX]