version: '3'

vars:
  DEFAULT_NFCORE_MODULE: nf-core/3.1.1

includes:
  envmodule:
    taskfile: ./EnvironmentModules.yml
    internal: true

tasks:
  download-nf-core-pipeline:
    desc: Downloading pipelines for offline use
    summary: |
      Downloading pipelines for offline use

      Notes
        - `--container-system` must be either "singularity" or "none"
        - containers are downloaded to $NXF_SINGULARITY_CACHEDIR by default
        - OUTDIR should not already exist

      URLs
        - [Docs](https://nf-co.re/docs/nf-core-tools/pipelines/download)
    vars:
      # Task options
      NFCORE_MODULE: '{{.NFCORE_MODULE | default .DEFAULT_NFCORE_MODULE}}'
      PATH_VERSION:
        sh: echo "{{.VERSION}}" | tr '.' '_'
      PATH: '{{.OUTDIR}}/{{.PATH_VERSION}}'

      # Options for `nf-core pipelines download ...`
      COMPRESS: '{{.COMPRESS | default "none"}}'
      CONTAINER_CACHE_UTILISATION: '{{.CONTAINER_CACHE_UTILISATION | default "amend"}}'
      CONTAINER_SYSTEM: '{{.CONTAINER_SYSTEM | default "singularity"}}'
      EXTRA: '{{.EXTRA | default ""}}'
      OUTDIR: '{{.OUTDIR}}'
    prompt: Download {{.PIPELINE}} to {{.PATH}}?
    cmds:
      - task: envmodule:run-inside
        vars:
          CMDS: |
            nf-core pipelines download {{.PIPELINE}} \
              -r {{.VERSION}} \
              --outdir {{.OUTDIR}} \
              --container-system {{.CONTAINER_SYSTEM}} \
              --container-cache-utilisation {{.CONTAINER_CACHE_UTILISATION}} \
              --compress {{.COMPRESS}} \
              {{.EXTRA}}
          MODULE: '{{.NFCORE_MODULE}}'
    requires:
      vars: [OUTDIR, PIPELINE, VERSION]
    generates:
      - '{{.PATH}}'
      - '{{.PATH}}/assets'
      - '{{.PATH}}/bin'
      - '{{.PATH}}/CHANGELOG.md'
      - '{{.PATH}}/CITATIONS.md'
      - '{{.PATH}}/CODE_OF_CONDUCT.md'
      - '{{.PATH}}/conf'
      - '{{.PATH}}/docs'
      - '{{.PATH}}/LICENSE'
      - '{{.PATH}}/main.nf'
      - '{{.PATH}}/modules'
      - '{{.PATH}}/modules.json'
      - '{{.PATH}}/nextflow.config'
      - '{{.PATH}}/nextflow_schema.json'
      - '{{.PATH}}/nf-test.config'
      - '{{.PATH}}/README.md'
      - '{{.PATH}}/subworkflows'
      - '{{.PATH}}/tests'
      - '{{.PATH}}/tower.yml'
      - '{{.PATH}}/workflows'
    status:
      - test -f '{{.PATH}}/main.nf'